"""add race sessions

Revision ID: 09f0a3fedbe2
Revises: ece05f2ea760
Create Date: 2026-08-31 11:01:02.876806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f0a3fedbe2'
down_revision: Union[str, Sequence[str], None] = 'ece05f2ea760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'kind')
    )
    op.create_index(op.f('ix_race_sessions_race_id'), 'race_sessions', ['race_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_race_sessions_race_id'), table_name='race_sessions')
    op.drop_table('race_sessions')
    # ### end Alembic commands ###
