"""add driver headshot url

Revision ID: 0b2240c61f57
Revises: 92108da62639
Create Date: 2026-03-14 21:27:48.039557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2240c61f57'
down_revision: Union[str, Sequence[str], None] = '92108da62639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('headshot_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'headshot_url')
    # ### end Alembic commands ###
