"""initial schema

Revision ID: 0f59c8043d16
Revises: 
Create Date: 2026-03-13 23:25:28.808561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f59c8043d16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuits_ref'), 'circuits', ['ref'], unique=True)
    op.create_table('constructors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constructors_ref'), 'constructors', ['ref'], unique=True)
    op.create_table('drivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_ref'), 'drivers', ['ref'], unique=True)
    op.create_table('seasons',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('circuit_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['season_year'], ['seasons.year'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_races_season_year'), 'races', ['season_year'], unique=False)
    op.create_table('constructor_standings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('constructor_id', sa.String(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constructor_standings_constructor_id'), 'constructor_standings', ['constructor_id'], unique=False)
    op.create_index(op.f('ix_constructor_standings_race_id'), 'constructor_standings', ['race_id'], unique=False)
    op.create_table('driver_standings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_standings_driver_id'), 'driver_standings', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_standings_race_id'), 'driver_standings', ['race_id'], unique=False)
    op.create_table('lap_times',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('time_millis', sa.BigInteger(), nullable=True),
    sa.Column('sector1_ms', sa.BigInteger(), nullable=True),
    sa.Column('sector2_ms', sa.BigInteger(), nullable=True),
    sa.Column('sector3_ms', sa.BigInteger(), nullable=True),
    sa.Column('compound', sa.String(), nullable=True),
    sa.Column('stint', sa.Integer(), nullable=True),
    sa.Column('tyre_life', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lap_times_driver_id'), 'lap_times', ['driver_id'], unique=False)
    op.create_index(op.f('ix_lap_times_race_id'), 'lap_times', ['race_id'], unique=False)
    op.create_table('pit_stops',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('stop_number', sa.Integer(), nullable=False),
    sa.Column('lap', sa.Integer(), nullable=False),
    sa.Column('time_of_day', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pit_stops_driver_id'), 'pit_stops', ['driver_id'], unique=False)
    op.create_index(op.f('ix_pit_stops_race_id'), 'pit_stops', ['race_id'], unique=False)
    op.create_table('qualifying_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('constructor_id', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('q1', sa.String(), nullable=True),
    sa.Column('q2', sa.String(), nullable=True),
    sa.Column('q3', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualifying_results_driver_id'), 'qualifying_results', ['driver_id'], unique=False)
    op.create_index(op.f('ix_qualifying_results_race_id'), 'qualifying_results', ['race_id'], unique=False)
    op.create_table('race_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('constructor_id', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('grid', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('time_text', sa.String(), nullable=True),
    sa.Column('time_millis', sa.BigInteger(), nullable=True),
    sa.Column('fastest_lap', sa.Integer(), nullable=True),
    sa.Column('fastest_lap_time', sa.String(), nullable=True),
    sa.Column('fastest_lap_speed', sa.String(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_results_driver_id'), 'race_results', ['driver_id'], unique=False)
    op.create_index(op.f('ix_race_results_race_id'), 'race_results', ['race_id'], unique=False)
    op.create_table('sprint_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('constructor_id', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('grid', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('laps', sa.Integer(), nullable=True),
    sa.Column('time_text', sa.String(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprint_results_driver_id'), 'sprint_results', ['driver_id'], unique=False)
    op.create_index(op.f('ix_sprint_results_race_id'), 'sprint_results', ['race_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sprint_results_race_id'), table_name='sprint_results')
    op.drop_index(op.f('ix_sprint_results_driver_id'), table_name='sprint_results')
    op.drop_table('sprint_results')
    op.drop_index(op.f('ix_race_results_race_id'), table_name='race_results')
    op.drop_index(op.f('ix_race_results_driver_id'), table_name='race_results')
    op.drop_table('race_results')
    op.drop_index(op.f('ix_qualifying_results_race_id'), table_name='qualifying_results')
    op.drop_index(op.f('ix_qualifying_results_driver_id'), table_name='qualifying_results')
    op.drop_table('qualifying_results')
    op.drop_index(op.f('ix_pit_stops_race_id'), table_name='pit_stops')
    op.drop_index(op.f('ix_pit_stops_driver_id'), table_name='pit_stops')
    op.drop_table('pit_stops')
    op.drop_index(op.f('ix_lap_times_race_id'), table_name='lap_times')
    op.drop_index(op.f('ix_lap_times_driver_id'), table_name='lap_times')
    op.drop_table('lap_times')
    op.drop_index(op.f('ix_driver_standings_race_id'), table_name='driver_standings')
    op.drop_index(op.f('ix_driver_standings_driver_id'), table_name='driver_standings')
    op.drop_table('driver_standings')
    op.drop_index(op.f('ix_constructor_standings_race_id'), table_name='constructor_standings')
    op.drop_index(op.f('ix_constructor_standings_constructor_id'), table_name='constructor_standings')
    op.drop_table('constructor_standings')
    op.drop_index(op.f('ix_races_season_year'), table_name='races')
    op.drop_table('races')
    op.drop_table('statuses')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_drivers_ref'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_constructors_ref'), table_name='constructors')
    op.drop_table('constructors')
    op.drop_index(op.f('ix_circuits_ref'), table_name='circuits')
    op.drop_table('circuits')
    # ### end Alembic commands ###
