"""add constructor has_logo column

Revision ID: 247f678364c8
Revises: 6391e77484c7
Create Date: 2026-03-14 23:22:07.639495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247f678364c8'
down_revision: Union[str, Sequence[str], None] = '6391e77484c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constructors', sa.Column('has_logo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('constructors', 'has_logo')
    # ### end Alembic commands ###
