"""add precomputed fastest lap and qualifying sector columns to races

Revision ID: 40b636f140ae
Revises: 6d62f6ef604f
Create Date: 2026-03-15 02:40:51.051701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b636f140ae'
down_revision: Union[str, Sequence[str], None] = '6d62f6ef604f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('fastest_lap_driver_id', sa.String(), nullable=True))
    op.add_column('races', sa.Column('fastest_lap_constructor_id', sa.String(), nullable=True))
    op.add_column('races', sa.Column('fastest_lap_number', sa.Integer(), nullable=True))
    op.add_column('races', sa.Column('fastest_lap_time', sa.String(), nullable=True))
    op.add_column('races', sa.Column('fastest_lap_time_ms', sa.BigInteger(), nullable=True))
    op.add_column('races', sa.Column('fastest_lap_speed', sa.String(), nullable=True))
    op.add_column('races', sa.Column('best_quali_s1_driver_id', sa.String(), nullable=True))
    op.add_column('races', sa.Column('best_quali_s1_ms', sa.BigInteger(), nullable=True))
    op.add_column('races', sa.Column('best_quali_s2_driver_id', sa.String(), nullable=True))
    op.add_column('races', sa.Column('best_quali_s2_ms', sa.BigInteger(), nullable=True))
    op.add_column('races', sa.Column('best_quali_s3_driver_id', sa.String(), nullable=True))
    op.add_column('races', sa.Column('best_quali_s3_ms', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'races', 'drivers', ['best_quali_s3_driver_id'], ['id'])
    op.create_foreign_key(None, 'races', 'drivers', ['best_quali_s2_driver_id'], ['id'])
    op.create_foreign_key(None, 'races', 'drivers', ['best_quali_s1_driver_id'], ['id'])
    op.create_foreign_key(None, 'races', 'constructors', ['fastest_lap_constructor_id'], ['id'])
    op.create_foreign_key(None, 'races', 'drivers', ['fastest_lap_driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'races', type_='foreignkey')
    op.drop_constraint(None, 'races', type_='foreignkey')
    op.drop_constraint(None, 'races', type_='foreignkey')
    op.drop_constraint(None, 'races', type_='foreignkey')
    op.drop_constraint(None, 'races', type_='foreignkey')
    op.drop_column('races', 'best_quali_s3_ms')
    op.drop_column('races', 'best_quali_s3_driver_id')
    op.drop_column('races', 'best_quali_s2_ms')
    op.drop_column('races', 'best_quali_s2_driver_id')
    op.drop_column('races', 'best_quali_s1_ms')
    op.drop_column('races', 'best_quali_s1_driver_id')
    op.drop_column('races', 'fastest_lap_speed')
    op.drop_column('races', 'fastest_lap_time_ms')
    op.drop_column('races', 'fastest_lap_time')
    op.drop_column('races', 'fastest_lap_number')
    op.drop_column('races', 'fastest_lap_constructor_id')
    op.drop_column('races', 'fastest_lap_driver_id')
    # ### end Alembic commands ###
