"""replace headshot_url with has_headshot boolean

Revision ID: 6391e77484c7
Revises: d9a3fc4f0e88
Create Date: 2026-03-14 22:39:40.440096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6391e77484c7'
down_revision: Union[str, Sequence[str], None] = 'd9a3fc4f0e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable first so we can backfill
    op.add_column('drivers', sa.Column('has_headshot', sa.Boolean(), nullable=True))

    # Backfill: True where headshot_url was set, False otherwise
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE drivers SET has_headshot = (headshot_url LIKE '/headshots/%')"))

    # Now make non-nullable with default
    op.alter_column('drivers', 'has_headshot', nullable=False, server_default=sa.text('false'))
    op.drop_column('drivers', 'headshot_url')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('headshot_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('drivers', 'has_headshot')
    # ### end Alembic commands ###
