"""add qualifying sector columns

Revision ID: 6d62f6ef604f
Revises: 247f678364c8
Create Date: 2026-03-15 02:31:49.507395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d62f6ef604f'
down_revision: Union[str, Sequence[str], None] = '247f678364c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qualifying_results', sa.Column('q1_s1_ms', sa.BigInteger(), nullable=True))
    op.add_column('qualifying_results', sa.Column('q1_s2_ms', sa.BigInteger(), nullable=True))
    op.add_column('qualifying_results', sa.Column('q1_s3_ms', sa.BigInteger(), nullable=True))
    op.add_column('qualifying_results', sa.Column('q2_s1_ms', sa.BigInteger(), nullable=True))
    op.add_column('qualifying_results', sa.Column('q2_s2_ms', sa.BigInteger(), nullable=True))
    op.add_column('qualifying_results', sa.Column('q2_s3_ms', sa.BigInteger(), nullable=True))
    op.add_column('qualifying_results', sa.Column('q3_s1_ms', sa.BigInteger(), nullable=True))
    op.add_column('qualifying_results', sa.Column('q3_s2_ms', sa.BigInteger(), nullable=True))
    op.add_column('qualifying_results', sa.Column('q3_s3_ms', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qualifying_results', 'q3_s3_ms')
    op.drop_column('qualifying_results', 'q3_s2_ms')
    op.drop_column('qualifying_results', 'q3_s1_ms')
    op.drop_column('qualifying_results', 'q2_s3_ms')
    op.drop_column('qualifying_results', 'q2_s2_ms')
    op.drop_column('qualifying_results', 'q2_s1_ms')
    op.drop_column('qualifying_results', 'q1_s3_ms')
    op.drop_column('qualifying_results', 'q1_s2_ms')
    op.drop_column('qualifying_results', 'q1_s1_ms')
    # ### end Alembic commands ###
