"""add unique constraints and missing indexes

Revision ID: 88d74c1cf0b8
Revises: 40b636f140ae
Create Date: 2026-03-16 19:16:13.857351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d74c1cf0b8'
down_revision: Union[str, Sequence[str], None] = '40b636f140ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_constructor_standings_position'), 'constructor_standings', ['position'], unique=False)
    op.create_unique_constraint(None, 'constructor_standings', ['race_id', 'constructor_id'])
    op.create_index(op.f('ix_driver_standings_position'), 'driver_standings', ['position'], unique=False)
    op.create_unique_constraint(None, 'driver_standings', ['race_id', 'driver_id'])
    op.create_unique_constraint(None, 'lap_times', ['race_id', 'driver_id', 'lap_number'])
    op.create_unique_constraint(None, 'pit_stops', ['race_id', 'driver_id', 'stop_number'])
    op.create_index(op.f('ix_qualifying_results_position'), 'qualifying_results', ['position'], unique=False)
    op.create_unique_constraint(None, 'qualifying_results', ['race_id', 'driver_id'])
    op.create_index(op.f('ix_race_results_constructor_id'), 'race_results', ['constructor_id'], unique=False)
    op.create_index(op.f('ix_race_results_position'), 'race_results', ['position'], unique=False)
    op.create_unique_constraint(None, 'race_results', ['race_id', 'driver_id'])
    op.create_index(op.f('ix_races_circuit_id'), 'races', ['circuit_id'], unique=False)
    op.create_unique_constraint(None, 'sprint_results', ['race_id', 'driver_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sprint_results', type_='unique')
    op.drop_index(op.f('ix_races_circuit_id'), table_name='races')
    op.drop_constraint(None, 'race_results', type_='unique')
    op.drop_index(op.f('ix_race_results_position'), table_name='race_results')
    op.drop_index(op.f('ix_race_results_constructor_id'), table_name='race_results')
    op.drop_constraint(None, 'qualifying_results', type_='unique')
    op.drop_index(op.f('ix_qualifying_results_position'), table_name='qualifying_results')
    op.drop_constraint(None, 'pit_stops', type_='unique')
    op.drop_constraint(None, 'lap_times', type_='unique')
    op.drop_constraint(None, 'driver_standings', type_='unique')
    op.drop_index(op.f('ix_driver_standings_position'), table_name='driver_standings')
    op.drop_constraint(None, 'constructor_standings', type_='unique')
    op.drop_index(op.f('ix_constructor_standings_position'), table_name='constructor_standings')
    # ### end Alembic commands ###
