"""add circuit layouts table

Revision ID: 92108da62639
Revises: 0f59c8043d16
Create Date: 2026-03-14 13:36:17.421304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92108da62639'
down_revision: Union[str, Sequence[str], None] = '0f59c8043d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit_layouts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('circuit_id', sa.String(), nullable=False),
    sa.Column('layout_number', sa.Integer(), nullable=False),
    sa.Column('svg_id', sa.String(), nullable=False),
    sa.Column('seasons_active', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_layouts_circuit_id'), 'circuit_layouts', ['circuit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_circuit_layouts_circuit_id'), table_name='circuit_layouts')
    op.drop_table('circuit_layouts')
    # ### end Alembic commands ###
