"""add country_code columns

Revision ID: d9a3fc4f0e88
Revises: 0b2240c61f57
Create Date: 2026-03-14 22:27:32.507623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9a3fc4f0e88'
down_revision: Union[str, Sequence[str], None] = '0b2240c61f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('circuits', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.add_column('constructors', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.add_column('drivers', sa.Column('country_code', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###

    # Backfill country_code from existing nationality/country values
    from src.api.country_codes import _MAPPING

    conn = op.get_bind()
    # Drivers & constructors: nationality → country_code
    for table, col in [("drivers", "nationality"), ("constructors", "nationality"), ("circuits", "country")]:
        for value, code in _MAPPING.items():
            conn.execute(
                sa.text(f"UPDATE {table} SET country_code = :code WHERE {col} = :value AND country_code IS NULL"),
                {"code": code, "value": value},
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'country_code')
    op.drop_column('constructors', 'country_code')
    op.drop_column('circuits', 'country_code')
    # ### end Alembic commands ###
