"""add country_code columns

Revision ID: d9a3fc4f0e88
Revises: 0b2240c61f57
Create Date: 2026-03-14 22:27:32.507623

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9a3fc4f0e88"
down_revision: str | Sequence[str] | None = "0b2240c61f57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Snapshot of src/api/country_codes.py as it existed when this migration was
# written. Inlined so the migration stays runnable after that module was
# removed: migrations must never import live application code.
_MAPPING: dict[str, str] = {
    # Nationalities
    "British": "GB",
    "German": "DE",
    "Brazilian": "BR",
    "Spanish": "ES",
    "Finnish": "FI",
    "Dutch": "NL",
    "French": "FR",
    "Italian": "IT",
    "Australian": "AU",
    "Japanese": "JP",
    "Canadian": "CA",
    "Austrian": "AT",
    "Mexican": "MX",
    "Monegasque": "MC",
    "Danish": "DK",
    "Thai": "TH",
    "Chinese": "CN",
    "American": "US",
    "Argentine": "AR",
    "Belgian": "BE",
    "Swiss": "CH",
    "New Zealander": "NZ",
    "Colombian": "CO",
    "Polish": "PL",
    "Swedish": "SE",
    "Portuguese": "PT",
    "Indian": "IN",
    "Russian": "RU",
    "South African": "ZA",
    "Venezuelan": "VE",
    "Irish": "IE",
    "Rhodesian": "ZW",
    "Hungarian": "HU",
    "Czech": "CZ",
    "Malaysian": "MY",
    "Indonesian": "ID",
    "Uruguayan": "UY",
    "Chilean": "CL",
    "Liechtensteiner": "LI",
    "East German": "DE",
    "Moroccan": "MA",
    "Hong Kongese": "HK",
    # Countries
    "UK": "GB",
    "United Kingdom": "GB",
    "Germany": "DE",
    "Brazil": "BR",
    "Spain": "ES",
    "Finland": "FI",
    "Netherlands": "NL",
    "France": "FR",
    "Italy": "IT",
    "Australia": "AU",
    "Japan": "JP",
    "Canada": "CA",
    "Austria": "AT",
    "Mexico": "MX",
    "Monaco": "MC",
    "Denmark": "DK",
    "Thailand": "TH",
    "China": "CN",
    "USA": "US",
    "United States": "US",
    "Argentina": "AR",
    "Belgium": "BE",
    "Switzerland": "CH",
    "New Zealand": "NZ",
    "Colombia": "CO",
    "Poland": "PL",
    "Sweden": "SE",
    "Portugal": "PT",
    "India": "IN",
    "Russia": "RU",
    "South Africa": "ZA",
    "Venezuela": "VE",
    "Ireland": "IE",
    "Hungary": "HU",
    "Czech Republic": "CZ",
    "Malaysia": "MY",
    "Indonesia": "ID",
    "Uruguay": "UY",
    "Chile": "CL",
    "Bahrain": "BH",
    "Saudi Arabia": "SA",
    "Singapore": "SG",
    "Azerbaijan": "AZ",
    "Qatar": "QA",
    "United Arab Emirates": "AE",
    "UAE": "AE",
    "Turkey": "TR",
    "Korea": "KR",
    "South Korea": "KR",
    "Morocco": "MA",
    "Hong Kong": "HK",
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("circuits", sa.Column("country_code", sa.String(length=2), nullable=True))
    op.add_column("constructors", sa.Column("country_code", sa.String(length=2), nullable=True))
    op.add_column("drivers", sa.Column("country_code", sa.String(length=2), nullable=True))
    # ### end Alembic commands ###

    # Backfill country_code from existing nationality/country values
    conn = op.get_bind()
    # Drivers & constructors: nationality → country_code
    for table, col in (
        ("drivers", "nationality"),
        ("constructors", "nationality"),
        ("circuits", "country"),
    ):
        for value, code in _MAPPING.items():
            conn.execute(
                sa.text(
                    f"UPDATE {table} SET country_code = :code "
                    f"WHERE {col} = :value AND country_code IS NULL"
                ),
                {"code": code, "value": value},
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("drivers", "country_code")
    op.drop_column("constructors", "country_code")
    op.drop_column("circuits", "country_code")
    # ### end Alembic commands ###
