"""add race weather and race control messages

Revision ID: ece05f2ea760
Revises: 88d74c1cf0b8
Create Date: 2026-08-31 10:42:03.588195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece05f2ea760'
down_revision: Union[str, Sequence[str], None] = '88d74c1cf0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_control_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('utc', sa.DateTime(), nullable=True),
    sa.Column('lap', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('sector', sa.Integer(), nullable=True),
    sa.Column('driver_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'utc', 'message')
    )
    op.create_index(op.f('ix_race_control_messages_lap'), 'race_control_messages', ['lap'], unique=False)
    op.create_index(op.f('ix_race_control_messages_race_id'), 'race_control_messages', ['race_id'], unique=False)
    op.create_table('race_weather',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('race_id', sa.String(), nullable=False),
    sa.Column('session_time_ms', sa.BigInteger(), nullable=False),
    sa.Column('air_temp', sa.Float(), nullable=True),
    sa.Column('track_temp', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=True),
    sa.Column('rainfall', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'session_time_ms')
    )
    op.create_index(op.f('ix_race_weather_race_id'), 'race_weather', ['race_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_race_weather_race_id'), table_name='race_weather')
    op.drop_table('race_weather')
    op.drop_index(op.f('ix_race_control_messages_race_id'), table_name='race_control_messages')
    op.drop_index(op.f('ix_race_control_messages_lap'), table_name='race_control_messages')
    op.drop_table('race_control_messages')
    # ### end Alembic commands ###
