import fs from 'node:fs/promises'
import path from 'node:path'

import { PageHeader } from '@/components/ui/page-header'
import { Card, CardContent } from '@/components/ui/card'
import { FadeIn } from '@/components/ui/motion'

export const metadata = {
  title: 'Attributions',
  description:
    'Data sources, licences and trademark notices for F1 Tracker — an unofficial, non-commercial Formula 1 fan project.',
}

interface WikimediaCredit {
  file: string
  source_page: string
  author: string
  license: string
  license_url?: string
  attribution?: string
  modified?: string
}

interface SourceEntry {
  name: string
  href: string
  used: string
  licence: string
  licenceHref?: string
}

const DATA_SOURCES: SourceEntry[] = [
  {
    name: 'jolpica-f1 (Ergast successor)',
    href: 'https://github.com/jolpica/jolpica-f1',
    used: 'Seasons, races, circuits, drivers, constructors, results, qualifying, sprint, pit stops and standings',
    licence: 'CC BY-NC-SA 4.0',
    licenceHref: 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
  },
  {
    name: 'Fast-F1',
    href: 'https://github.com/theOehrly/Fast-F1',
    used: 'API client, plus lap times, tyre stints and qualifying sector times (2018+)',
    licence: 'MIT',
    licenceHref: 'https://github.com/theOehrly/Fast-F1/blob/master/LICENSE',
  },
  {
    name: 'OpenF1',
    href: 'https://openf1.org/',
    used: 'Driver headshots for the current era (2023+)',
    licence: 'Non-commercial use',
    licenceHref: 'https://openf1.org/',
  },
  {
    name: 'TheSportsDB',
    href: 'https://www.thesportsdb.com/',
    used: 'Team badges for the current grid, reproduced unmodified',
    licence: 'TheSportsDB terms',
    licenceHref: 'https://www.thesportsdb.com/docs_terms_of_use.php',
  },
  {
    name: 'Wikidata & Wikimedia Commons',
    href: 'https://commons.wikimedia.org/',
    used: 'Photographs of historic drivers and logos of defunct constructors',
    licence: 'Per file — see below',
    licenceHref: 'https://commons.wikimedia.org/wiki/Commons:Licensing',
  },
  {
    name: 'f1-circuits-svg by julesr0y',
    href: 'https://github.com/julesr0y/f1-circuits-svg',
    used: 'Circuit layout drawings',
    licence: 'CC BY 4.0',
    licenceHref: 'https://creativecommons.org/licenses/by/4.0/',
  },
  {
    name: 'OpenStreetMap & CARTO',
    href: 'https://www.openstreetmap.org/copyright',
    used: 'Basemap tiles behind the circuit world map',
    licence: 'ODbL / CARTO basemap terms',
    licenceHref: 'https://carto.com/attributions',
  },
]

async function loadWikimediaCredits(): Promise<WikimediaCredit[]> {
  try {
    const file = path.join(process.cwd(), 'public', 'credits', 'wikimedia-credits.json')
    const raw = await fs.readFile(file, 'utf8')
    const parsed = JSON.parse(raw) as Record<string, WikimediaCredit>
    return Object.values(parsed).sort((a, b) => a.file.localeCompare(b.file))
  } catch {
    // Manifest is generated by the image ingestors; absent on a fresh checkout.
    return []
  }
}

export default async function AttributionsPage() {
  const wikimediaCredits = await loadWikimediaCredits()

  return (
    <div className="space-y-10">
      <PageHeader
        title="Attributions"
        description="F1 Tracker is an unofficial, non-commercial fan project. Every data source and image it uses is credited here."
      />

      <FadeIn>
        <Card className="border-primary/40">
          <CardContent className="space-y-3 pt-6 text-sm leading-relaxed">
            <h2 className="font-heading text-base font-bold tracking-wider uppercase">
              Trademark notice
            </h2>
            <p className="text-muted-foreground">
              F1 Tracker is unofficial and is not associated in any way with the Formula 1
              companies. F1, FORMULA ONE, FORMULA 1, FIA FORMULA ONE WORLD CHAMPIONSHIP, GRAND PRIX
              and related marks are trade marks of Formula One Licensing B.V.
            </p>
            <p className="text-muted-foreground">
              Constructor names and team logos are trade marks of their respective owners, and are
              reproduced here for identification and editorial purposes only.
            </p>
          </CardContent>
        </Card>
      </FadeIn>

      <FadeIn>
        <section className="space-y-4">
          <h2 className="font-heading text-lg font-bold tracking-wider uppercase">Sources</h2>
          <div className="grid gap-4 md:grid-cols-2">
            {DATA_SOURCES.map((source) => (
              <Card key={source.name}>
                <CardContent className="space-y-2 pt-6">
                  <a
                    href={source.href}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-primary font-semibold hover:underline"
                  >
                    {source.name}
                  </a>
                  <p className="text-muted-foreground text-sm">{source.used}</p>
                  <p className="text-xs">
                    <span className="text-muted-foreground">Licence: </span>
                    {source.licenceHref ? (
                      <a
                        href={source.licenceHref}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="hover:underline"
                      >
                        {source.licence}
                      </a>
                    ) : (
                      source.licence
                    )}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>
      </FadeIn>

      <FadeIn>
        <section className="space-y-4">
          <h2 className="font-heading text-lg font-bold tracking-wider uppercase">
            Data licence &amp; reuse
          </h2>
          <Card>
            <CardContent className="text-muted-foreground space-y-3 pt-6 text-sm leading-relaxed">
              <p>
                Formula 1 results data comes from the{' '}
                <a
                  href="https://github.com/jolpica/jolpica-f1"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-foreground hover:underline"
                >
                  jolpica-f1 API
                </a>{' '}
                (successor to the Ergast Developer API), licensed{' '}
                <a
                  href="https://creativecommons.org/licenses/by-nc-sa/4.0/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-foreground hover:underline"
                >
                  CC BY-NC-SA 4.0
                </a>
                . It has been modified: reshaped into a relational schema and augmented with derived
                statistics.
              </p>
              <p>
                Under ShareAlike, the dataset published by this project is offered under the same CC
                BY-NC-SA 4.0 licence. That licence is{' '}
                <strong className="text-foreground">non-commercial</strong>: this site carries no
                advertising, no paid tier and no sponsorship, and any reuse of its data must stay
                non-commercial too.
              </p>
              <p>
                The project&apos;s own source code is MIT licensed. Bundled images are not — each
                carries the licence of its own rights holder.
              </p>
            </CardContent>
          </Card>
        </section>
      </FadeIn>

      {wikimediaCredits.length > 0 && (
        <FadeIn>
          <section className="space-y-4">
            <h2 className="font-heading text-lg font-bold tracking-wider uppercase">
              Wikimedia Commons images
            </h2>
            <p className="text-muted-foreground text-sm">
              {wikimediaCredits.length} images sourced from Wikimedia Commons, each under its own
              licence.
            </p>
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead className="text-muted-foreground border-b">
                  <tr>
                    <th className="py-2 pr-4 font-semibold">File</th>
                    <th className="py-2 pr-4 font-semibold">Author</th>
                    <th className="py-2 pr-4 font-semibold">Licence</th>
                    <th className="py-2 font-semibold">Changes</th>
                  </tr>
                </thead>
                <tbody>
                  {wikimediaCredits.map((credit) => (
                    <tr key={credit.file} className="border-b">
                      <td className="py-2 pr-4">
                        <a
                          href={credit.source_page}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="hover:underline"
                        >
                          {credit.file}
                        </a>
                      </td>
                      <td className="text-muted-foreground py-2 pr-4">{credit.author}</td>
                      <td className="py-2 pr-4">
                        {credit.license_url ? (
                          <a
                            href={credit.license_url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="hover:underline"
                          >
                            {credit.license}
                          </a>
                        ) : (
                          credit.license
                        )}
                      </td>
                      <td className="text-muted-foreground py-2">{credit.modified ?? 'None'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>
        </FadeIn>
      )}

      <FadeIn>
        <section className="space-y-3">
          <h2 className="font-heading text-lg font-bold tracking-wider uppercase">
            Rights holders
          </h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            If you hold rights to something used here and believe it is used improperly, please open
            an issue at{' '}
            <a
              href="https://github.com/hugoogb/f1-tracker/issues"
              target="_blank"
              rel="noopener noreferrer"
              className="text-foreground hover:underline"
            >
              github.com/hugoogb/f1-tracker
            </a>{' '}
            and it will be removed promptly.
          </p>
        </section>
      </FadeIn>
    </div>
  )
}
