export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000/api'

export const TEAM_COLORS: Record<string, string> = {
  red_bull: '#3671C6',
  mercedes: '#27F4D2',
  ferrari: '#E8002D',
  mclaren: '#FF8000',
  aston_martin: '#229971',
  alpine: '#FF87BC',
  williams: '#64C4FF',
  haas: '#B6BABD',
  rb: '#6692FF',
  sauber: '#52E252',
} as const

export const COUNTRY_FLAGS: Record<string, string> = {
  // Nationalities
  British: '🇬🇧',
  German: '🇩🇪',
  Brazilian: '🇧🇷',
  Spanish: '🇪🇸',
  Finnish: '🇫🇮',
  Dutch: '🇳🇱',
  French: '🇫🇷',
  Italian: '🇮🇹',
  Australian: '🇦🇺',
  Japanese: '🇯🇵',
  Canadian: '🇨🇦',
  Austrian: '🇦🇹',
  Mexican: '🇲🇽',
  Monegasque: '🇲🇨',
  Danish: '🇩🇰',
  Thai: '🇹🇭',
  Chinese: '🇨🇳',
  American: '🇺🇸',
  Argentine: '🇦🇷',
  Belgian: '🇧🇪',
  Swiss: '🇨🇭',
  'New Zealander': '🇳🇿',
  Colombian: '🇨🇴',
  Polish: '🇵🇱',
  Swedish: '🇸🇪',
  Portuguese: '🇵🇹',
  Indian: '🇮🇳',
  Russian: '🇷🇺',
  'South African': '🇿🇦',
  Venezuelan: '🇻🇪',
  Irish: '🇮🇪',
  Rhodesian: '🇿🇼',
  Hungarian: '🇭🇺',
  Czech: '🇨🇿',
  Malaysian: '🇲🇾',
  Indonesian: '🇮🇩',
  Uruguayan: '🇺🇾',
  Chilean: '🇨🇱',
  Liechtensteiner: '🇱🇮',
  // Countries
  UK: '🇬🇧',
  Germany: '🇩🇪',
  Brazil: '🇧🇷',
  Spain: '🇪🇸',
  Finland: '🇫🇮',
  Netherlands: '🇳🇱',
  France: '🇫🇷',
  Italy: '🇮🇹',
  Australia: '🇦🇺',
  Japan: '🇯🇵',
  Canada: '🇨🇦',
  Austria: '🇦🇹',
  Mexico: '🇲🇽',
  Monaco: '🇲🇨',
  Denmark: '🇩🇰',
  Thailand: '🇹🇭',
  China: '🇨🇳',
  USA: '🇺🇸',
  'United States': '🇺🇸',
  Argentina: '🇦🇷',
  Belgium: '🇧🇪',
  Switzerland: '🇨🇭',
  'New Zealand': '🇳🇿',
  Colombia: '🇨🇴',
  Poland: '🇵🇱',
  Sweden: '🇸🇪',
  Portugal: '🇵🇹',
  India: '🇮🇳',
  Russia: '🇷🇺',
  'South Africa': '🇿🇦',
  Venezuela: '🇻🇪',
  Ireland: '🇮🇪',
  Hungary: '🇭🇺',
  'Czech Republic': '🇨🇿',
  Malaysia: '🇲🇾',
  Indonesia: '🇮🇩',
  Uruguay: '🇺🇾',
  Chile: '🇨🇱',
  Bahrain: '🇧🇭',
  'Saudi Arabia': '🇸🇦',
  Singapore: '🇸🇬',
  Azerbaijan: '🇦🇿',
  Qatar: '🇶🇦',
  'United Arab Emirates': '🇦🇪',
  UAE: '🇦🇪',
  Turkey: '🇹🇷',
  Korea: '🇰🇷',
  'South Korea': '🇰🇷',
} as const
