import type { Metadata } from 'next'

/**
 * Canonical origin for the deployed site. Absolute URLs are required for
 * Open Graph/Twitter images and `rel=canonical`, and crawlers ignore relative
 * ones, so everything SEO-facing is resolved against this.
 */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ?? 'https://f1-tracker-web.vercel.app'
).replace(/\/$/, '')

export const SITE_NAME = 'F1 Tracker'

export const SITE_DESCRIPTION =
  'Explore the complete history of Formula 1 — every season, driver, constructor and circuit since 1950, with interactive analytics, standings, race results and head-to-head comparisons.'

/** Brand red, kept in sync with `--primary` in globals.css. */
export const THEME_COLOR = '#E10600'

export const absoluteUrl = (path = '/') => `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`

/**
 * The site-wide social card generated by `app/opengraph-image.tsx`. Next only
 * folds that file convention in for pages that do not declare `openGraph`
 * themselves, and every page below does — so it has to be attached explicitly.
 */
const OG_IMAGE = {
  url: absoluteUrl('/opengraph-image'),
  width: 1200,
  height: 630,
  alt: `${SITE_NAME} — Formula 1 history, stats and analytics`,
}

interface SeoInput {
  /** Page title without the site suffix — the root template appends it. */
  title: string
  description: string
  /** Site-relative path used for `rel=canonical` and the Open Graph URL. */
  path: string
  /** Query-driven or otherwise low-value pages: keep them out of the index. */
  noindex?: boolean
  /** Open Graph type; `article` suits dated content such as a race result. */
  type?: 'website' | 'article' | 'profile'
}

/**
 * Builds a page's metadata with the canonical URL and the Open Graph/Twitter
 * cards filled in from the same title and description, so a page never ends up
 * sharing the root layout's generic card.
 */
export function buildMetadata({
  title,
  description,
  path,
  noindex = false,
  type = 'website',
}: SeoInput): Metadata {
  const url = absoluteUrl(path)
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title: `${title} | ${SITE_NAME}`,
      description,
      url,
      siteName: SITE_NAME,
      type,
      locale: 'en_US',
      images: [OG_IMAGE],
    },
    twitter: {
      card: 'summary_large_image',
      title: `${title} | ${SITE_NAME}`,
      description,
      images: [OG_IMAGE.url],
    },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
  }
}
