"""Map nationality/country strings to ISO 3166-1 alpha-2 codes."""

_MAPPING: dict[str, str] = {
    # Nationalities
    "British": "GB",
    "German": "DE",
    "Brazilian": "BR",
    "Spanish": "ES",
    "Finnish": "FI",
    "Dutch": "NL",
    "French": "FR",
    "Italian": "IT",
    "Australian": "AU",
    "Japanese": "JP",
    "Canadian": "CA",
    "Austrian": "AT",
    "Mexican": "MX",
    "Monegasque": "MC",
    "Danish": "DK",
    "Thai": "TH",
    "Chinese": "CN",
    "American": "US",
    "Argentine": "AR",
    "Belgian": "BE",
    "Swiss": "CH",
    "New Zealander": "NZ",
    "Colombian": "CO",
    "Polish": "PL",
    "Swedish": "SE",
    "Portuguese": "PT",
    "Indian": "IN",
    "Russian": "RU",
    "South African": "ZA",
    "Venezuelan": "VE",
    "Irish": "IE",
    "Rhodesian": "ZW",
    "Hungarian": "HU",
    "Czech": "CZ",
    "Malaysian": "MY",
    "Indonesian": "ID",
    "Uruguayan": "UY",
    "Chilean": "CL",
    "Liechtensteiner": "LI",
    "East German": "DE",
    "Moroccan": "MA",
    "Hong Kongese": "HK",
    # Countries
    "UK": "GB",
    "United Kingdom": "GB",
    "Germany": "DE",
    "Brazil": "BR",
    "Spain": "ES",
    "Finland": "FI",
    "Netherlands": "NL",
    "France": "FR",
    "Italy": "IT",
    "Australia": "AU",
    "Japan": "JP",
    "Canada": "CA",
    "Austria": "AT",
    "Mexico": "MX",
    "Monaco": "MC",
    "Denmark": "DK",
    "Thailand": "TH",
    "China": "CN",
    "USA": "US",
    "United States": "US",
    "Argentina": "AR",
    "Belgium": "BE",
    "Switzerland": "CH",
    "New Zealand": "NZ",
    "Colombia": "CO",
    "Poland": "PL",
    "Sweden": "SE",
    "Portugal": "PT",
    "India": "IN",
    "Russia": "RU",
    "South Africa": "ZA",
    "Venezuela": "VE",
    "Ireland": "IE",
    "Hungary": "HU",
    "Czech Republic": "CZ",
    "Malaysia": "MY",
    "Indonesia": "ID",
    "Uruguay": "UY",
    "Chile": "CL",
    "Bahrain": "BH",
    "Saudi Arabia": "SA",
    "Singapore": "SG",
    "Azerbaijan": "AZ",
    "Qatar": "QA",
    "United Arab Emirates": "AE",
    "UAE": "AE",
    "Turkey": "TR",
    "Korea": "KR",
    "South Korea": "KR",
    "Morocco": "MA",
    "Hong Kong": "HK",
}


def country_code(value: str | None) -> str | None:
    """Convert a nationality or country name to an ISO 3166-1 alpha-2 code."""
    if value is None:
        return None
    return _MAPPING.get(value)
